import * as esbuild from 'esbuild';
import * as path from 'path';
import * as fs from 'fs';
import { execSync } from 'child_process';
import esbuildPluginTsc from 'esbuild-plugin-tsc';

const __dirname = path.dirname(new URL(import.meta.url).pathname);

// Function to find all files with a specific extension in a directory
function findFiles(dir, extension) {
  let filelist = [];
  try {
    const files = fs.readdirSync(dir);
    files.forEach(file => {
      const filepath = path.join(dir, file);
      try {
        if (fs.statSync(filepath).isDirectory()) {
          if (file !== 'node_modules') {
            filelist = filelist.concat(findFiles(filepath, extension));
          }
        } else if (filepath.endsWith(extension)) {
          filelist.push(filepath);
        }
      }
      catch (e) {
        // ignore stat errors
      }
    });
  }
  catch (e) {
    // ignore readdir errors
  }
  return filelist;
}

function generateModuleDeclarations() {
    console.log('Generating module declarations for deep imports...');
    const packageName = '@dooboostore/simple-boot-front';
    const typesDir = path.resolve(__dirname, 'dist/types');
    const outputFile = path.resolve(__dirname, 'types.d.ts');

    if (!fs.existsSync(typesDir)) {
        console.error(`Error: '${typesDir}' not found. Run tsc to generate declaration files first.`);
        process.exit(1);
    }

    const dtsFiles = findFiles(typesDir, '.d.ts');
    let declarations = `// Generated by build.mjs\n// This file provides module declarations for better IDE auto-import support.\n\n`;
    const declaredModules = new Set();

    for (const file of dtsFiles) {
        const relativePath = path.relative(typesDir, file);
        let modulePath = relativePath.replace(/\\/g, '/').replace(/\.d\.ts$/, '');

        if (path.basename(modulePath) === 'index') {
            modulePath = path.dirname(modulePath);
        }

        if (modulePath === '.' || modulePath === 'index' || modulePath.includes('bundle-entry')) {
            continue;
        }

        const moduleName = `${packageName}/${modulePath}`;
        if (declaredModules.has(moduleName)) {
            continue;
        }
        declaredModules.add(moduleName);

        const fileContent = fs.readFileSync(file, 'utf8');
        const fixedContent = fileContent.replace(/(from\s+['"])\.(.+?['"])/g, (match, p1, p2) => {
            const importPath = path.join(path.dirname(modulePath), p2.substring(0, p2.length - 1));
            return `${p1}${packageName}/${importPath}"`;
        });

        declarations += `declare module "${moduleName}" {\n`;
        declarations += fixedContent.split('\n').map(line => `  ${line}`).join('\n');
        declarations += `\n}\n\n`;
    }

    fs.writeFileSync(outputFile, declarations);
    console.log(`✅ Module declarations written to ${path.relative(process.cwd(), outputFile)}`);
}

function addSubmoduleReferences() {
    const typesDir = path.resolve(__dirname, 'dist/types');
    const indexPath = path.resolve(typesDir, 'index.d.ts');

    if (!fs.existsSync(indexPath)) {
        console.warn(`Warning: ${indexPath} not found. Skipping adding submodule references.`);
        return;
    }

    try {
        const subdirs = fs.readdirSync(typesDir, { withFileTypes: true })
            .filter(dirent => dirent.isDirectory())
            .map(dirent => dirent.name);

        let directives = '';
        for (const dir of subdirs) {
            const subDirFullPath = path.resolve(typesDir, dir);
            const dtsFilesInSubdir = fs.readdirSync(subDirFullPath)
                .filter(file => file.endsWith('.d.ts'));

            for (const dtsFile of dtsFilesInSubdir) {
                directives += `/// <reference path="${dir}/${dtsFile}" />\n`;
            }
        }

        if (directives) {
            let content = fs.readFileSync(indexPath, 'utf8');
            // Remove old directives if any, to prevent duplicates or outdated references
            content = content.replace(/(\/\/\/\s*<reference\s*path=".*"\s*\/>\n)+/, '');
            content = directives + content;
            fs.writeFileSync(indexPath, content, 'utf8');
            console.log(`✅ Added submodule reference directives to ${path.relative(process.cwd(), indexPath)}`);
        }
    } catch (e) {
        console.error('Failed to add submodule reference directives:', e);
    }
}

const declarationGeneratorPlugin = {
    name: 'declaration-generator',
    setup(build) {
        build.onEnd(result => {
            if (result.errors.length === 0) {
                console.log('Build successful, generating declarations...');
                try {
                    execSync('pnpm exec tsc -p tsconfig.json --emitDeclarationOnly', { stdio: 'inherit' });
                    generateModuleDeclarations();
                    addSubmoduleReferences();
                } catch (e) {
                    console.error('Declaration generation failed:', e);
                }
            }
        });
    }
};

// Function to add .js extension to relative imports/exports in generated JS files
function addJsExtensionToImports(dir) {
  const files = fs.readdirSync(dir);
  files.forEach(file => {
    const filepath = path.join(dir, file);
    if (fs.statSync(filepath).isDirectory()) {
      addJsExtensionToImports(filepath); // Recurse into subdirectories
    } else if (filepath.endsWith('.js')) {
      let content = fs.readFileSync(filepath, 'utf8');
      // Regex to find import/export statements with relative paths
      // and without a file extension (or with .ts extension)
      const regex = /(import|export)([\s\S]*?from\s+['"])((\.?\.?\/|\/)[^'"]+)(['"];)/g;
      content = content.replace(regex, (match, p1, p2, p3, p4, p5) => {
        if (!p3.endsWith('.js') && !p3.endsWith('.json') && !p3.endsWith('.mjs') && !p3.endsWith('.cjs')) {
          const absoluteImportPath = path.resolve(path.dirname(filepath), p3);
          if (fs.existsSync(absoluteImportPath) && fs.statSync(absoluteImportPath).isDirectory()) {
            return p1 + p2 + p3 + '/index.js' + p5;
          } else {
            return p1 + p2 + p3 + '.js' + p5;
          }
        }
        return match;
      });
      fs.writeFileSync(filepath, content, 'utf8');
    }
  });
}

const srcDir = path.resolve(__dirname, 'src');
const tsFiles = findFiles(srcDir, '.ts');

const entryPoints = tsFiles.reduce((acc, file) => {
  const entryName = path.relative(srcDir, file).replace(/\.ts$/, '');
  acc[entryName] = file;
  return acc;
}, {});

async function performBuild(options, watch) {
  if (watch) {
    const context = await esbuild.context(options);
    await context.watch();
    console.log('Watching for changes...');
  } else {
    await esbuild.build(options);
    if (options.format === 'esm' && options.outdir) {
      console.log('Adding .js extensions to ESM imports...');
      addJsExtensionToImports(options.outdir);
    }
  }
}

async function buildTarget(target, watch = false) {
  const baseOptions = {
    bundle: true, // Always bundle for web
    sourcemap: true,
    target: 'es2020', // Target modern browsers
    platform: 'browser', // Build for browser environment
  };
    // Define a plugin to run after each build
    const addJsExtensionPlugin = {
        name: 'add-js-extension',
        setup(build) {
            build.onEnd(result => {
                if (result.errors.length === 0 && build.initialOptions.format === 'esm' && build.initialOptions.outdir) {
                    console.log('Adding .js extensions to ESM imports after build...');
                    addJsExtensionToImports(build.initialOptions.outdir);
                }
            });
        },
    };
  switch (target) {
    case 'esm':
      console.log('Starting ESM build...');
      await performBuild({
        ...baseOptions,
         bundle: false,
        entryPoints: entryPoints,
        outdir: path.resolve(__dirname, 'dist', 'esm'),
        format: 'esm',
        resolveExtensions: ['.ts', '.tsx', '.js', '.jsx', '.json'],
        mainFields: ['module', 'main'],
        plugins: [esbuildPluginTsc({tsconfigPath:'tsconfig.esm.json'}), addJsExtensionPlugin, declarationGeneratorPlugin],
      }, watch);
      console.log('ESM build complete.');
      break;
    case 'cjs':
      console.log('Starting CJS build...');
      await performBuild({
        ...baseOptions,
         bundle: false,
        entryPoints: entryPoints,
        outdir: path.resolve(__dirname, 'dist', 'cjs'),
        format: 'cjs',
        plugins: [esbuildPluginTsc({tsconfigPath:'tsconfig.cjs.json'}),declarationGeneratorPlugin],
      }, watch);
      console.log('CJS build complete.');
      break;
    case 'umd-bundle':
      console.log('Starting UMD bundle build...');
      await performBuild({
        ...baseOptions,
          bundle:true,
        entryPoints: [path.resolve(srcDir, 'bundle-entry.ts')],
        outfile: path.resolve(__dirname, 'dist', 'umd-bundle', 'dooboostore-simple-boot-front.umd.js'),
        format: 'iife',
        globalName: 'dooboostoreSimpleBootFront',
        plugins: [esbuildPluginTsc({tsconfigPath:'tsconfig.umd.json'})],
        // tsconfig: 'tsconfig.umd.json',
      }, watch);
      console.log('UMD bundle build complete.');
      break;
    case 'esm-bundle':
      console.log('Starting ESM bundle build...');
      await performBuild({
        ...baseOptions,
          bundle:true,
        entryPoints: [path.resolve(srcDir, 'bundle-entry.ts')],
        outfile: path.resolve(__dirname, 'dist', 'esm-bundle', 'dooboostore-simple-boot-front.esm.js'),
        format: 'esm',
        plugins: [esbuildPluginTsc({tsconfigPath:'tsconfig.esm.json'})],
        // tsconfig: 'tsconfig.esm.json',
      }, watch);
      console.log('ESM bundle build complete.');
      break;
    case 'all':
      if (!watch) { // Only clean if not in watch mode
        fs.rmSync(path.resolve(__dirname, 'dist'), { recursive: true, force: true });
      }
      await buildTarget('esm', watch);
      await buildTarget('cjs', watch);
      await buildTarget('umd-bundle', watch);
      await buildTarget('esm-bundle', watch);
      break;
    default:
      console.error('Invalid build target specified.');
      process.exit(1);
  }
}

const args = process.argv.slice(2);
const target = args[0] || 'all';
const watch = args.includes('--watch');

buildTarget(target, watch).catch((error) => {
  console.error('Build process failed:', error);
  process.exit(1);
});