import { Code } from './Code';

export enum IOS3166_1_Code {
GHA = 'GHA',
GAB = 'GAB',
GUY = 'GUY',
GMB = 'GMB',
GGY = 'GGY',
GLP = 'GLP',
GTM = 'GTM',
GUM = 'GUM',
GRD = 'GRD',
GRC = 'GRC',
GRL = 'GRL',
GIN = 'GIN',
GNB = 'GNB',
NAM = 'NAM',
NRU = 'NRU',
NGA = 'NGA',
ATA = 'ATA',
SSD = 'SSD',
ZAF = 'ZAF',
NLD = 'NLD',
NPL = 'NPL',
NOR = 'NOR',
NFK = 'NFK',
NCL = 'NCL',
NZL = 'NZL',
NIU = 'NIU',
NER = 'NER',
NIC = 'NIC',
KOR = 'KOR',
DNK = 'DNK',
DOM = 'DOM',
DMA = 'DMA',
DEU = 'DEU',
TLS = 'TLS',
LAO = 'LAO',
LBR = 'LBR',
LVA = 'LVA',
RUS = 'RUS',
LBN = 'LBN',
LSO = 'LSO',
REU = 'REU',
ROU = 'ROU',
LUX = 'LUX',
RWA = 'RWA',
LBY = 'LBY',
LTU = 'LTU',
LIE = 'LIE',
MDG = 'MDG',
MTQ = 'MTQ',
MHL = 'MHL',
MYT = 'MYT',
MAC = 'MAC',
MKD = 'MKD',
MWI = 'MWI',
MYS = 'MYS',
MLI = 'MLI',
IMN = 'IMN',
MEX = 'MEX',
MCO = 'MCO',
MAR = 'MAR',
MUS = 'MUS',
MRT = 'MRT',
MOZ = 'MOZ',
MNE = 'MNE',
MSR = 'MSR',
MDA = 'MDA',
MDV = 'MDV',
MLT = 'MLT',
MNG = 'MNG',
USA = 'USA',
UMI = 'UMI',
VIR = 'VIR',
MMR = 'MMR',
FSM = 'FSM',
VUT = 'VUT',
BHR = 'BHR',
BRB = 'BRB',
VAT = 'VAT',
BHS = 'BHS',
BGD = 'BGD',
BMU = 'BMU',
BEN = 'BEN',
VEN = 'VEN',
VNM = 'VNM',
BEL = 'BEL',
BLR = 'BLR',
BLZ = 'BLZ',
BES = 'BES',
BIH = 'BIH',
BWA = 'BWA',
BOL = 'BOL',
BDI = 'BDI',
BFA = 'BFA',
BVT = 'BVT',
BTN = 'BTN',
MNP = 'MNP',
BGR = 'BGR',
BRA = 'BRA',
BRN = 'BRN',
WSM = 'WSM',
SAU = 'SAU',
SGS = 'SGS',
SMR = 'SMR',
STP = 'STP',
MAF = 'MAF',
BLM = 'BLM',
SPM = 'SPM',
ESH = 'ESH',
SEN = 'SEN',
SRB = 'SRB',
SYC = 'SYC',
LCA = 'LCA',
VCT = 'VCT',
KNA = 'KNA',
SHN = 'SHN',
SOM = 'SOM',
SLB = 'SLB',
SDN = 'SDN',
SUR = 'SUR',
LKA = 'LKA',
SJM = 'SJM',
SWE = 'SWE',
CHE = 'CHE',
ESP = 'ESP',
SVK = 'SVK',
SVN = 'SVN',
SYR = 'SYR',
SLE = 'SLE',
SXM = 'SXM',
SGP = 'SGP',
ARE = 'ARE',
ABW = 'ABW',
ARM = 'ARM',
ARG = 'ARG',
ASM = 'ASM',
ISL = 'ISL',
HTI = 'HTI',
IRL = 'IRL',
AZE = 'AZE',
AFG = 'AFG',
AND = 'AND',
ALB = 'ALB',
DZA = 'DZA',
AGO = 'AGO',
ATG = 'ATG',
AIA = 'AIA',
ERI = 'ERI',
SWZ = 'SWZ',
EST = 'EST',
ECU = 'ECU',
ETH = 'ETH',
SLV = 'SLV',
GBR = 'GBR',
VGB = 'VGB',
IOT = 'IOT',
YEM = 'YEM',
OMN = 'OMN',
AUS = 'AUS',
AUT = 'AUT',
HND = 'HND',
ALA = 'ALA',
JOR = 'JOR',
UGA = 'UGA',
URY = 'URY',
UZB = 'UZB',
UKR = 'UKR',
WLF = 'WLF',
IRQ = 'IRQ',
IRN = 'IRN',
ISR = 'ISR',
EGY = 'EGY',
ITA = 'ITA',
IND = 'IND',
IDN = 'IDN',
JPN = 'JPN',
JAM = 'JAM',
ZMB = 'ZMB',
JEY = 'JEY',
GNQ = 'GNQ',
PRK = 'PRK',
GEO = 'GEO',
CHN = 'CHN',
CAF = 'CAF',
DJI = 'DJI',
GIB = 'GIB',
ZWE = 'ZWE',
TCD = 'TCD',
CZE = 'CZE',
CHL = 'CHL',
CMR = 'CMR',
CPV = 'CPV',
KAZ = 'KAZ',
QAT = 'QAT',
KHM = 'KHM',
CAN = 'CAN',
KEN = 'KEN',
CYM = 'CYM',
COM = 'COM',
CRI = 'CRI',
CCK = 'CCK',
CIV = 'CIV',
COL = 'COL',
COG = 'COG',
COD = 'COD',
CUB = 'CUB',
KWT = 'KWT',
COK = 'COK',
CUW = 'CUW',
HRV = 'HRV',
CXR = 'CXR',
KGZ = 'KGZ',
KIR = 'KIR',
CYP = 'CYP',
TWN = 'TWN',
TJK = 'TJK',
TZA = 'TZA',
THA = 'THA',
TCA = 'TCA',
TUR = 'TUR',
TGO = 'TGO',
TKL = 'TKL',
TON = 'TON',
TKM = 'TKM',
TUV = 'TUV',
TUN = 'TUN',
TTO = 'TTO',
PAN = 'PAN',
PRY = 'PRY',
PAK = 'PAK',
PNG = 'PNG',
PLW = 'PLW',
PSE = 'PSE',
FRO = 'FRO',
PER = 'PER',
PRT = 'PRT',
FLK = 'FLK',
POL = 'POL',
PRI = 'PRI',
FRA = 'FRA',
GUF = 'GUF',
ATF = 'ATF',
PYF = 'PYF',
FJI = 'FJI',
FIN = 'FIN',
PHL = 'PHL',
PCN = 'PCN',
HMD = 'HMD',
HUN = 'HUN',
HKG = 'HKG',
}


export type IOS3166_1_CodeDescriptionDataType = { alpha3: string, alpha2: string, emoji: string, img: string, num: number, en: string, ko: string };
export const IOS3166_1_CodeDescription: Record<IOS3166_1_Code, Code<IOS3166_1_CodeDescriptionDataType>> = {
  [IOS3166_1_Code.GHA]: { description: '', data: {emoji:'🇬🇭', alpha2: 'GH', alpha3:'GHA', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/22px-Flag_of_Ghana.svg.png',ko:'가나', num:288,en:'Ghana'} },
  [IOS3166_1_Code.GAB]: { description: '', data: {emoji:'🇬🇦', alpha2: 'GA', alpha3:'GAB', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Flag_of_Gabon.svg/40px-Flag_of_Gabon.svg.png',ko:'가봉', num:266,en:'Gabon'} },
  [IOS3166_1_Code.GUY]: { description: '', data: {emoji:'🇬🇾', alpha2: 'GY', alpha3:'GUY', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_Guyana.svg/40px-Flag_of_Guyana.svg.png',ko:'가이아나', num:328,en:'Guyana'} },
  [IOS3166_1_Code.GMB]: { description: '', data: {emoji:'🇬🇲', alpha2: 'GM', alpha3:'GMB', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_The_Gambia.svg/40px-Flag_of_The_Gambia.svg.png',ko:'감비아', num:270,en:'Gambia'} },
  [IOS3166_1_Code.GGY]: { description: '', data: {emoji:'🇬🇬', alpha2: 'GG', alpha3:'GGY', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Guernsey.svg/40px-Flag_of_Guernsey.svg.png',ko:'건지섬', num:831,en:'Guernsey Island'} },
  [IOS3166_1_Code.GLP]: { description: '', data: {emoji:'🇬🇵', alpha2: 'GP', alpha3:'GLP', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Flag_of_France_%282020%E2%80%93present%29.svg/22px-Flag_of_France_%282020%E2%80%93present%29.svg.png',ko:'과들루프', num:312,en:'Guadeloupe'} },
  [IOS3166_1_Code.GTM]: { description: '', data: {emoji:'🇬🇹', alpha2: 'GT', alpha3:'GTM', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Flag_of_Guatemala.svg/40px-Flag_of_Guatemala.svg.png',ko:'과테말라', num:320,en:'Guatemala'} },
  [IOS3166_1_Code.GUM]: { description: '', data: {emoji:'🇬🇺', alpha2: 'GU', alpha3:'GUM', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Flag_of_Guam.svg/40px-Flag_of_Guam.svg.png',ko:'괌', num:316,en:'Guam'} },
  [IOS3166_1_Code.GRD]: { description: '', data: {emoji:'🇬🇩', alpha2: 'GD', alpha3:'GRD', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Grenada.svg/22px-Flag_of_Grenada.svg.png',ko:'그레나다', num:308,en:'Grenada'} },
  [IOS3166_1_Code.GRC]: { description: '', data: {emoji:'🇬🇷', alpha2: 'GR', alpha3:'GRC', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/40px-Flag_of_Greece.svg.png',ko:'그리스', num:300,en:'Greece'} },
  [IOS3166_1_Code.GRL]: { description: '', data: {emoji:'🇬🇱', alpha2: 'GL', alpha3:'GRL', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_Greenland.svg/22px-Flag_of_Greenland.svg.png',ko:'그린란드', num:304,en:'Greenland'} },
  [IOS3166_1_Code.GIN]: { description: '', data: {emoji:'🇬🇳', alpha2: 'GN', alpha3:'GIN', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Flag_of_Guinea.svg/22px-Flag_of_Guinea.svg.png',ko:'기니', num:324,en:'Guineas'} },
  [IOS3166_1_Code.GNB]: { description: '', data: {emoji:'🇬🇼', alpha2: 'GW', alpha3:'GNB', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Guinea-Bissau.svg/22px-Flag_of_Guinea-Bissau.svg.png',ko:'기니비사우', num:624,en:'Guinea-Bissau'} },
  [IOS3166_1_Code.NAM]: { description: '', data: {emoji:'🇳🇦', alpha2: 'NA', alpha3:'NAM', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Namibia.svg/22px-Flag_of_Namibia.svg.png',ko:'나미비아', num:516,en:'Namibia'} },
  [IOS3166_1_Code.NRU]: { description: '', data: {emoji:'🇳🇷', alpha2: 'NR', alpha3:'NRU', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Flag_of_Nauru.svg/40px-Flag_of_Nauru.svg.png',ko:'나우루', num:520,en:'Nauru'} },
  [IOS3166_1_Code.NGA]: { description: '', data: {emoji:'🇳🇬', alpha2: 'NG', alpha3:'NGA', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/22px-Flag_of_Nigeria.svg.png',ko:'나이지리아', num:566,en:'Nigeria'} },
  [IOS3166_1_Code.ATA]: { description: '', data: {emoji:'🇦🇶', alpha2: 'AQ', alpha3:'ATA', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Proposed_flag_of_Antarctica_%28Graham_Bartram%29.svg/40px-Proposed_flag_of_Antarctica_%28Graham_Bartram%29.svg.png',ko:'남극', num:10,en:'Antarctica'} },
  [IOS3166_1_Code.SSD]: { description: '', data: {emoji:'🇸🇸', alpha2: 'SS', alpha3:'SSD', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Flag_of_South_Sudan.svg/40px-Flag_of_South_Sudan.svg.png',ko:'남수단', num:728,en:'South Sudan'} },
  [IOS3166_1_Code.ZAF]: { description: '', data: {emoji:'🇿🇦', alpha2: 'ZA', alpha3:'ZAF', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/40px-Flag_of_South_Africa.svg.png',ko:'남아프리카 공화국', num:710,en:'South Africa'} },
  [IOS3166_1_Code.NLD]: { description: '', data: {emoji:'🇳🇱', alpha2: 'NL', alpha3:'NLD', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/22px-Flag_of_the_Netherlands.svg.png',ko:'네덜란드', num:528,en:'Netherlands'} },
  [IOS3166_1_Code.NPL]: { description: '', data: {emoji:'🇳🇵', alpha2: 'NP', alpha3:'NPL', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Flag_of_Nepal.svg/20px-Flag_of_Nepal.svg.png',ko:'네팔', num:524,en:'Nepal'} },
  [IOS3166_1_Code.NOR]: { description: '', data: {emoji:'🇳🇴', alpha2: 'NO', alpha3:'NOR', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/40px-Flag_of_Norway.svg.png',ko:'노르웨이', num:578,en:'Norway'} },
  [IOS3166_1_Code.NFK]: { description: '', data: {emoji:'🇳🇫', alpha2: 'NF', alpha3:'NFK', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Norfolk_Island.svg/22px-Flag_of_Norfolk_Island.svg.png',ko:'노퍽섬', num:574,en:'Norfolk Island'} },
  [IOS3166_1_Code.NCL]: { description: '', data: {emoji:'🇳🇨', alpha2: 'NC', alpha3:'NCL', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flags_of_New_Caledonia.svg/60px-Flags_of_New_Caledonia.svg.png',ko:'누벨칼레도니', num:540,en:'Nouvel Caledoni'} },
  [IOS3166_1_Code.NZL]: { description: '', data: {emoji:'🇳🇿', alpha2: 'NZ', alpha3:'NZL', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Flag_of_New_Zealand.svg/40px-Flag_of_New_Zealand.svg.png',ko:'뉴질랜드', num:554,en:'New Zealand'} },
  [IOS3166_1_Code.NIU]: { description: '', data: {emoji:'🇳🇺', alpha2: 'NU', alpha3:'NIU', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Niue.svg/22px-Flag_of_Niue.svg.png',ko:'니우에', num:570,en:'in the near future'} },
  [IOS3166_1_Code.NER]: { description: '', data: {emoji:'🇳🇪', alpha2: 'NE', alpha3:'NER', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Flag_of_Niger.svg/40px-Flag_of_Niger.svg.png',ko:'니제르', num:562,en:'Niger'} },
  [IOS3166_1_Code.NIC]: { description: '', data: {emoji:'🇳🇮', alpha2: 'NI', alpha3:'NIC', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Nicaragua.svg/40px-Flag_of_Nicaragua.svg.png',ko:'니카라과', num:558,en:'Nicaragua'} },
  [IOS3166_1_Code.KOR]: { description: '', data: {emoji:'🇰🇷', alpha2: 'KR', alpha3:'KOR', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/40px-Flag_of_South_Korea.svg.png',ko:'대한민국', num:410,en:'Republic of Korea'} },
  [IOS3166_1_Code.DNK]: { description: '', data: {emoji:'🇩🇰', alpha2: 'DK', alpha3:'DNK', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/22px-Flag_of_Denmark.svg.png',ko:'덴마크', num:208,en:'Denmark'} },
  [IOS3166_1_Code.DOM]: { description: '', data: {emoji:'🇩🇴', alpha2: 'DO', alpha3:'DOM', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_the_Dominican_Republic.svg/40px-Flag_of_the_Dominican_Republic.svg.png',ko:'도미니카 공화국', num:214,en:'Dominican Republic'} },
  [IOS3166_1_Code.DMA]: { description: '', data: {emoji:'🇩🇲', alpha2: 'DM', alpha3:'DMA', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Flag_of_Dominica.svg/22px-Flag_of_Dominica.svg.png',ko:'도미니카 연방', num:212,en:'Union of Dominicans'} },
  [IOS3166_1_Code.DEU]: { description: '', data: {emoji:'🇩🇪', alpha2: 'DE', alpha3:'DEU', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/22px-Flag_of_Germany.svg.png',ko:'독일', num:276,en:'Germany'} },
  [IOS3166_1_Code.TLS]: { description: '', data: {emoji:'🇹🇱', alpha2: 'TL', alpha3:'TLS', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flag_of_East_Timor.svg/40px-Flag_of_East_Timor.svg.png',ko:'동티모르', num:626,en:'East Timor'} },
  [IOS3166_1_Code.LAO]: { description: '', data: {emoji:'🇱🇦', alpha2: 'LA', alpha3:'LAO', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Laos.svg/40px-Flag_of_Laos.svg.png',ko:'라오스', num:418,en:'Laos'} },
  [IOS3166_1_Code.LBR]: { description: '', data: {emoji:'🇱🇷', alpha2: 'LR', alpha3:'LBR', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Flag_of_Liberia.svg/40px-Flag_of_Liberia.svg.png',ko:'라이베리아', num:430,en:'Liberia'} },
  [IOS3166_1_Code.LVA]: { description: '', data: {emoji:'🇱🇻', alpha2: 'LV', alpha3:'LVA', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Latvia.svg/40px-Flag_of_Latvia.svg.png',ko:'라트비아', num:428,en:'Latvia'} },
  [IOS3166_1_Code.RUS]: { description: '', data: {emoji:'🇷🇺', alpha2: 'RU', alpha3:'RUS', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Russia.svg/40px-Flag_of_Russia.svg.png',ko:'러시아', num:643,en:'Russia'} },
  [IOS3166_1_Code.LBN]: { description: '', data: {emoji:'🇱🇧', alpha2: 'LB', alpha3:'LBN', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/40px-Flag_of_Lebanon.svg.png',ko:'레바논', num:422,en:'Lebanon'} },
  [IOS3166_1_Code.LSO]: { description: '', data: {emoji:'🇱🇸', alpha2: 'LS', alpha3:'LSO', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Flag_of_Lesotho.svg/40px-Flag_of_Lesotho.svg.png',ko:'레소토', num:426,en:'Lesotho'} },
  [IOS3166_1_Code.REU]: { description: '', data: {emoji:'🇷🇪', alpha2: 'RE', alpha3:'REU', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Flag_of_France_%282020%E2%80%93present%29.svg/22px-Flag_of_France_%282020%E2%80%93present%29.svg.png',ko:'레위니옹', num:638,en:'Réunion'} },
  [IOS3166_1_Code.ROU]: { description: '', data: {emoji:'🇷🇴', alpha2: 'RO', alpha3:'ROU', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/22px-Flag_of_Romania.svg.png',ko:'루마니아', num:642,en:'Romania'} },
  [IOS3166_1_Code.LUX]: { description: '', data: {emoji:'🇱🇺', alpha2: 'LU', alpha3:'LUX', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Flag_of_Luxembourg.svg/40px-Flag_of_Luxembourg.svg.png',ko:'룩셈부르크', num:442,en:'Luxembourg'} },
  [IOS3166_1_Code.RWA]: { description: '', data: {emoji:'🇷🇼', alpha2: 'RW', alpha3:'RWA', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/22px-Flag_of_Rwanda.svg.png',ko:'르완다', num:646,en:'Rwanda'} },
  [IOS3166_1_Code.LBY]: { description: '', data: {emoji:'🇱🇾', alpha2: 'LY', alpha3:'LBY', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Libya.svg/40px-Flag_of_Libya.svg.png',ko:'리비아', num:434,en:'Libya'} },
  [IOS3166_1_Code.LTU]: { description: '', data: {emoji:'🇱🇹', alpha2: 'LT', alpha3:'LTU', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Lithuania.svg/40px-Flag_of_Lithuania.svg.png',ko:'리투아니아', num:440,en:'Lithuania'} },
  [IOS3166_1_Code.LIE]: { description: '', data: {emoji:'🇱🇮', alpha2: 'LI', alpha3:'LIE', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Flag_of_Liechtenstein.svg/40px-Flag_of_Liechtenstein.svg.png',ko:'리히텐슈타인', num:438,en:'Liechtenstein'} },
  [IOS3166_1_Code.MDG]: { description: '', data: {emoji:'🇲🇬', alpha2: 'MG', alpha3:'MDG', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Madagascar.svg/40px-Flag_of_Madagascar.svg.png',ko:'마다가스카르', num:450,en:'Madagascar.'} },
  [IOS3166_1_Code.MTQ]: { description: '', data: {emoji:'🇲🇶', alpha2: 'MQ', alpha3:'MTQ', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag-of-Martinique.svg/22px-Flag-of-Martinique.svg.png',ko:'마르티니크', num:474,en:'Martinique'} },
  [IOS3166_1_Code.MHL]: { description: '', data: {emoji:'🇲🇭', alpha2: 'MH', alpha3:'MHL', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Flag_of_the_Marshall_Islands.svg/40px-Flag_of_the_Marshall_Islands.svg.png',ko:'마셜 제도', num:584,en:'Marshall Islands'} },
  [IOS3166_1_Code.MYT]: { description: '', data: {emoji:'🇾🇹', alpha2: 'YT', alpha3:'MYT', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Flag_of_France_%282020%E2%80%93present%29.svg/22px-Flag_of_France_%282020%E2%80%93present%29.svg.png',ko:'마요트', num:175,en:'Mayotte'} },
  [IOS3166_1_Code.MAC]: { description: '', data: {emoji:'🇲🇴', alpha2: 'MO', alpha3:'MAC', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Flag_of_Macau.svg/40px-Flag_of_Macau.svg.png',ko:'마카오', num:446,en:'Macau'} },
  [IOS3166_1_Code.MKD]: { description: '', data: {emoji:'🇲🇰', alpha2: 'MK', alpha3:'MKD', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_North_Macedonia.svg/40px-Flag_of_North_Macedonia.svg.png',ko:'북마케도니아', num:807,en:'North Macedonia'} },
  [IOS3166_1_Code.MWI]: { description: '', data: {emoji:'🇲🇼', alpha2: 'MW', alpha3:'MWI', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Flag_of_Malawi.svg/22px-Flag_of_Malawi.svg.png',ko:'말라위', num:454,en:'Malawi'} },
  [IOS3166_1_Code.MYS]: { description: '', data: {emoji:'🇲🇾', alpha2: 'MY', alpha3:'MYS', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Flag_of_Malaysia.svg/22px-Flag_of_Malaysia.svg.png',ko:'말레이시아', num:458,en:'Malaysia'} },
  [IOS3166_1_Code.MLI]: { description: '', data: {emoji:'🇲🇱', alpha2: 'ML', alpha3:'MLI', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Mali.svg/40px-Flag_of_Mali.svg.png',ko:'말리', num:466,en:'Marley'} },
  [IOS3166_1_Code.IMN]: { description: '', data: {emoji:'🇮🇲', alpha2: 'IM', alpha3:'IMN', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Flag_of_the_Isle_of_Mann.svg/40px-Flag_of_the_Isle_of_Mann.svg.png',ko:'맨섬', num:833,en:'Isle of Man'} },
  [IOS3166_1_Code.MEX]: { description: '', data: {emoji:'🇲🇽', alpha2: 'MX', alpha3:'MEX', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/40px-Flag_of_Mexico.svg.png',ko:'멕시코', num:484,en:'Mexico'} },
  [IOS3166_1_Code.MCO]: { description: '', data: {emoji:'🇲🇨', alpha2: 'MC', alpha3:'MCO', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Flag_of_Monaco.svg/22px-Flag_of_Monaco.svg.png',ko:'모나코', num:492,en:'Monaco'} },
  [IOS3166_1_Code.MAR]: { description: '', data: {emoji:'🇲🇦', alpha2: 'MA', alpha3:'MAR', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/40px-Flag_of_Morocco.svg.png',ko:'모로코', num:504,en:'Morocco, the Republic of Korea'} },
  [IOS3166_1_Code.MUS]: { description: '', data: {emoji:'🇲🇺', alpha2: 'MU', alpha3:'MUS', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Mauritius.svg/40px-Flag_of_Mauritius.svg.png',ko:'모리셔스', num:480,en:'Mauritius'} },
  [IOS3166_1_Code.MRT]: { description: '', data: {emoji:'🇲🇷', alpha2: 'MR', alpha3:'MRT', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Flag_of_Mauritania.svg/40px-Flag_of_Mauritania.svg.png',ko:'모리타니', num:478,en:'Mauritania'} },
  [IOS3166_1_Code.MOZ]: { description: '', data: {emoji:'🇲🇿', alpha2: 'MZ', alpha3:'MOZ', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Mozambique.svg/40px-Flag_of_Mozambique.svg.png',ko:'모잠비크', num:508,en:'Mozambique'} },
  [IOS3166_1_Code.MNE]: { description: '', data: {emoji:'🇲🇪', alpha2: 'ME', alpha3:'MNE', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Montenegro.svg/40px-Flag_of_Montenegro.svg.png',ko:'몬테네그로', num:499,en:'Montenegro'} },
  [IOS3166_1_Code.MSR]: { description: '', data: {emoji:'🇲🇸', alpha2: 'MS', alpha3:'MSR', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Montserrat.svg/22px-Flag_of_Montserrat.svg.png',ko:'몬트세랫', num:500,en:'Mont-Serrat'} },
  [IOS3166_1_Code.MDA]: { description: '', data: {emoji:'🇲🇩', alpha2: 'MD', alpha3:'MDA', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Moldova.svg/40px-Flag_of_Moldova.svg.png',ko:'몰도바', num:498,en:'Moldova'} },
  [IOS3166_1_Code.MDV]: { description: '', data: {emoji:'🇲🇻', alpha2: 'MV', alpha3:'MDV', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Maldives.svg/40px-Flag_of_Maldives.svg.png',ko:'몰디브', num:462,en:'Maldives'} },
  [IOS3166_1_Code.MLT]: { description: '', data: {emoji:'🇲🇹', alpha2: 'MT', alpha3:'MLT', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Malta.svg/22px-Flag_of_Malta.svg.png',ko:'몰타', num:470,en:'Malta'} },
  [IOS3166_1_Code.MNG]: { description: '', data: {emoji:'🇲🇳', alpha2: 'MN', alpha3:'MNG', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Mongolia.svg/22px-Flag_of_Mongolia.svg.png',ko:'몽골', num:496,en:'Mongolia'} },
  [IOS3166_1_Code.USA]: { description: '', data: {emoji:'🇺🇸', alpha2: 'US', alpha3:'USA', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/40px-Flag_of_the_United_States.svg.png',ko:'미국', num:840,en:'the United States'} },
  [IOS3166_1_Code.UMI]: { description: '', data: {emoji:'🇺🇲', alpha2: 'UM', alpha3:'UMI', img:'http://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/40px-Flag_of_the_United_States.svg.png',ko:'미국령 군소 제도', num:581,en:'the U.S. minor system'} },
  [IOS3166_1_Code.VIR]: { description: '', data: {emoji:'🇻🇮', alpha2: 'VI', alpha3:'VIR', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Flag_of_the_United_States_Virgin_Islands.svg/22px-Flag_of_the_United_States_Virgin_Islands.svg.png',ko:'미국령 버진아일랜드', num:850,en:'U.S. Virgin Islands'} },
  [IOS3166_1_Code.MMR]: { description: '', data: {emoji:'🇲🇲', alpha2: 'MM', alpha3:'MMR', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Flag_of_Myanmar.svg/22px-Flag_of_Myanmar.svg.png',ko:'미얀마', num:104,en:'Myanmar'} },
  [IOS3166_1_Code.FSM]: { description: '', data: {emoji:'🇫🇲', alpha2: 'FM', alpha3:'FSM', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Flag_of_the_Federated_States_of_Micronesia.svg/40px-Flag_of_the_Federated_States_of_Micronesia.svg.png',ko:'미크로네시아 연방', num:583,en:'Federation of Micronesia'} },
  [IOS3166_1_Code.VUT]: { description: '', data: {emoji:'🇻🇺', alpha2: 'VU', alpha3:'VUT', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Vanuatu.svg/22px-Flag_of_Vanuatu.svg.png',ko:'바누아투', num:548,en:'Vanuatu'} },
  [IOS3166_1_Code.BHR]: { description: '', data: {emoji:'🇧🇭', alpha2: 'BH', alpha3:'BHR', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Bahrain.svg/40px-Flag_of_Bahrain.svg.png',ko:'바레인', num:48,en:'Bahrain'} },
  [IOS3166_1_Code.BRB]: { description: '', data: {emoji:'🇧🇧', alpha2: 'BB', alpha3:'BRB', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Flag_of_Barbados.svg/40px-Flag_of_Barbados.svg.png',ko:'바베이도스', num:52,en:'Barbados'} },
  [IOS3166_1_Code.VAT]: { description: '', data: {emoji:'🇻🇦', alpha2: 'VA', alpha3:'VAT', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Flag_of_Vatican_City_%282023%E2%80%93present%29.svg/20px-Flag_of_Vatican_City_%282023%E2%80%93present%29.svg.png',ko:'바티칸 시국', num:336,en:'Vatican City'} },
  [IOS3166_1_Code.BHS]: { description: '', data: {emoji:'🇧🇸', alpha2: 'BS', alpha3:'BHS', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Flag_of_the_Bahamas.svg/40px-Flag_of_the_Bahamas.svg.png',ko:'바하마', num:44,en:'Bahamas'} },
  [IOS3166_1_Code.BGD]: { description: '', data: {emoji:'🇧🇩', alpha2: 'BD', alpha3:'BGD', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/22px-Flag_of_Bangladesh.svg.png',ko:'방글라데시', num:50,en:'Bangladesh'} },
  [IOS3166_1_Code.BMU]: { description: '', data: {emoji:'🇧🇲', alpha2: 'BM', alpha3:'BMU', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bermuda.svg/40px-Flag_of_Bermuda.svg.png',ko:'버뮤다', num:60,en:'Bermuda'} },
  [IOS3166_1_Code.BEN]: { description: '', data: {emoji:'🇧🇯', alpha2: 'BJ', alpha3:'BEN', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Benin.svg/22px-Flag_of_Benin.svg.png',ko:'베냉', num:204,en:'Benin'} },
  [IOS3166_1_Code.VEN]: { description: '', data: {emoji:'🇻🇪', alpha2: 'VE', alpha3:'VEN', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Venezuela.svg/40px-Flag_of_Venezuela.svg.png',ko:'베네수엘라', num:862,en:'Venezuela'} },
  [IOS3166_1_Code.VNM]: { description: '', data: {emoji:'🇻🇳', alpha2: 'VN', alpha3:'VNM', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/40px-Flag_of_Vietnam.svg.png',ko:'베트남', num:704,en:'Vietnam'} },
  [IOS3166_1_Code.BEL]: { description: '', data: {emoji:'🇧🇪', alpha2: 'BE', alpha3:'BEL', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Belgium_%28civil%29.svg/40px-Flag_of_Belgium_%28civil%29.svg.png',ko:'벨기에', num:56,en:'Belgium'} },
  [IOS3166_1_Code.BLR]: { description: '', data: {emoji:'🇧🇾', alpha2: 'BY', alpha3:'BLR', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Flag_of_Belarus.svg/40px-Flag_of_Belarus.svg.png',ko:'벨라루스', num:112,en:'Belarus'} },
  [IOS3166_1_Code.BLZ]: { description: '', data: {emoji:'🇧🇿', alpha2: 'BZ', alpha3:'BLZ', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Flag_of_Belize.svg/22px-Flag_of_Belize.svg.png',ko:'벨리즈', num:84,en:'Belize'} },
  [IOS3166_1_Code.BES]: { description: '', data: {emoji:'🇧🇶', alpha2: 'BQ', alpha3:'BES', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Flag_of_Bonaire.svg/40px-Flag_of_Bonaire.svg.png',ko:'보네르섬', num:535,en:'Bonner Island'} },
  [IOS3166_1_Code.BIH]: { description: '', data: {emoji:'🇧🇦', alpha2: 'BA', alpha3:'BIH', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bosnia_and_Herzegovina.svg/40px-Flag_of_Bosnia_and_Herzegovina.svg.png',ko:'보스니아 헤르체고비나', num:70,en:'Bosnia and Herzegovina'} },
  [IOS3166_1_Code.BWA]: { description: '', data: {emoji:'🇧🇼', alpha2: 'BW', alpha3:'BWA', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Botswana.svg/40px-Flag_of_Botswana.svg.png',ko:'보츠와나', num:72,en:'Botswana'} },
  [IOS3166_1_Code.BOL]: { description: '', data: {emoji:'🇧🇴', alpha2: 'BO', alpha3:'BOL', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Bolivia.svg/40px-Flag_of_Bolivia.svg.png',ko:'볼리비아', num:68,en:'Bolivia'} },
  [IOS3166_1_Code.BDI]: { description: '', data: {emoji:'🇧🇮', alpha2: 'BI', alpha3:'BDI', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/40px-Flag_of_Burundi.svg.png',ko:'부룬디', num:108,en:'Burundi'} },
  [IOS3166_1_Code.BFA]: { description: '', data: {emoji:'🇧🇫', alpha2: 'BF', alpha3:'BFA', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Burkina_Faso.svg/22px-Flag_of_Burkina_Faso.svg.png',ko:'부르키나파소', num:854,en:'Burkina Faso'} },
  [IOS3166_1_Code.BVT]: { description: '', data: {emoji:'🇧🇻', alpha2: 'BV', alpha3:'BVT', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/BOUVET.png/40px-BOUVET.png',ko:'부베섬', num:74,en:'island of Bube'} },
  [IOS3166_1_Code.BTN]: { description: '', data: {emoji:'🇧🇹', alpha2: 'BT', alpha3:'BTN', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Flag_of_Bhutan.svg/40px-Flag_of_Bhutan.svg.png',ko:'부탄', num:64,en:'Bhutan'} },
  [IOS3166_1_Code.MNP]: { description: '', data: {emoji:'🇲🇵', alpha2: 'MP', alpha3:'MNP', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Flag_of_the_Northern_Mariana_Islands.svg/22px-Flag_of_the_Northern_Mariana_Islands.svg.png',ko:'북마리아나 제도', num:580,en:'Northern Mariana Islands'} },
  [IOS3166_1_Code.BGR]: { description: '', data: {emoji:'🇧🇬', alpha2: 'BG', alpha3:'BGR', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/22px-Flag_of_Bulgaria.svg.png',ko:'불가리아', num:100,en:'Bulgaria'} },
  [IOS3166_1_Code.BRA]: { description: '', data: {emoji:'🇧🇷', alpha2: 'BR', alpha3:'BRA', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/40px-Flag_of_Brazil.svg.png',ko:'브라질', num:76,en:'Brazil'} },
  [IOS3166_1_Code.BRN]: { description: '', data: {emoji:'🇧🇳', alpha2: 'BN', alpha3:'BRN', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Brunei.svg/40px-Flag_of_Brunei.svg.png',ko:'브루나이', num:96,en:'Brunei'} },
  [IOS3166_1_Code.WSM]: { description: '', data: {emoji:'🇼🇸', alpha2: 'WS', alpha3:'WSM', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Samoa.svg/40px-Flag_of_Samoa.svg.png',ko:'사모아', num:882,en:'Samoa'} },
  [IOS3166_1_Code.SAU]: { description: '', data: {emoji:'🇸🇦', alpha2: 'SA', alpha3:'SAU', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/40px-Flag_of_Saudi_Arabia.svg.png',ko:'사우디아라비아', num:682,en:'Saudi Arabia'} },
  [IOS3166_1_Code.SGS]: { description: '', data: {emoji:'🇬🇸', alpha2: 'GS', alpha3:'SGS', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Flag_of_South_Georgia_and_the_South_Sandwich_Islands.svg/22px-Flag_of_South_Georgia_and_the_South_Sandwich_Islands.svg.png',ko:'사우스조지아 사우스샌드위치 제도', num:239,en:'South Georgia South Sandwich Islands'} },
  [IOS3166_1_Code.SMR]: { description: '', data: {emoji:'🇸🇲', alpha2: 'SM', alpha3:'SMR', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Flag_of_San_Marino.svg/22px-Flag_of_San_Marino.svg.png',ko:'산마리노', num:674,en:'San Marino'} },
  [IOS3166_1_Code.STP]: { description: '', data: {emoji:'🇸🇹', alpha2: 'ST', alpha3:'STP', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe.svg/22px-Flag_of_S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe.svg.png',ko:'상투메 프린시페', num:678,en:'Sao Tome Principe'} },
  [IOS3166_1_Code.MAF]: { description: '', data: {emoji:'🇲🇫', alpha2: 'MF', alpha3:'MAF', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Flag_of_France_%282020%E2%80%93present%29.svg/22px-Flag_of_France_%282020%E2%80%93present%29.svg.png',ko:'생마르탱', num:663,en:'Saint-Martin'} },
  [IOS3166_1_Code.BLM]: { description: '', data: {emoji:'🇧🇱', alpha2: 'BL', alpha3:'BLM', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Saint_Barth%C3%A9lemy_%28local%29.svg/40px-Flag_of_Saint_Barth%C3%A9lemy_%28local%29.svg.png',ko:'생바르텔레미', num:652,en:'Saint-Bartelemi'} },
  [IOS3166_1_Code.SPM]: { description: '', data: {emoji:'🇵🇲', alpha2: 'PM', alpha3:'SPM', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Flag_of_Saint-Pierre_and_Miquelon.svg/40px-Flag_of_Saint-Pierre_and_Miquelon.svg.png',ko:'생피에르 미클롱', num:666,en:'Saint-Pierre Michael Long'} },
  [IOS3166_1_Code.ESH]: { description: '', data: {emoji:'🇪🇭', alpha2: 'EH', alpha3:'ESH', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flag_of_the_Sahrawi_Arab_Democratic_Republic.svg/40px-Flag_of_the_Sahrawi_Arab_Democratic_Republic.svg.png',ko:'서사하라', num:732,en:'Speak'} },
  [IOS3166_1_Code.SEN]: { description: '', data: {emoji:'🇸🇳', alpha2: 'SN', alpha3:'SEN', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/40px-Flag_of_Senegal.svg.png',ko:'세네갈', num:686,en:'Senegal'} },
  [IOS3166_1_Code.SRB]: { description: '', data: {emoji:'🇷🇸', alpha2: 'RS', alpha3:'SRB', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/40px-Flag_of_Serbia.svg.png',ko:'세르비아', num:688,en:'Serbia'} },
  [IOS3166_1_Code.SYC]: { description: '', data: {emoji:'🇸🇨', alpha2: 'SC', alpha3:'SYC', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Seychelles.svg/22px-Flag_of_Seychelles.svg.png',ko:'세이셸', num:690,en:'Seychelles'} },
  [IOS3166_1_Code.LCA]: { description: '', data: {emoji:'🇱🇨', alpha2: 'LC', alpha3:'LCA', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Saint_Lucia.svg/40px-Flag_of_Saint_Lucia.svg.png',ko:'세인트루시아', num:662,en:'Saint Lucia'} },
  [IOS3166_1_Code.VCT]: { description: '', data: {emoji:'🇻🇨', alpha2: 'VC', alpha3:'VCT', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Flag_of_Saint_Vincent_and_the_Grenadines.svg/40px-Flag_of_Saint_Vincent_and_the_Grenadines.svg.png',ko:'세인트빈센트 그레나딘', num:670,en:'Saint Vincent and the Grenadines'} },
  [IOS3166_1_Code.KNA]: { description: '', data: {emoji:'🇰🇳', alpha2: 'KN', alpha3:'KNA', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Saint_Kitts_and_Nevis.svg/22px-Flag_of_Saint_Kitts_and_Nevis.svg.png',ko:'세인트키츠 네비스', num:659,en:'Saint Kitts and Nevis'} },
  [IOS3166_1_Code.SHN]: { description: '', data: {emoji:'🇸🇭', alpha2: 'SH', alpha3:'SHN', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Saint_Helena.svg/40px-Flag_of_Saint_Helena.svg.png',ko:'세인트헬레나', num:654,en:'Saint Helena'} },
  [IOS3166_1_Code.SOM]: { description: '', data: {emoji:'🇸🇴', alpha2: 'SO', alpha3:'SOM', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_Somalia.svg/22px-Flag_of_Somalia.svg.png',ko:'소말리아', num:706,en:'Somalia'} },
  [IOS3166_1_Code.SLB]: { description: '', data: {emoji:'🇸🇧', alpha2: 'SB', alpha3:'SLB', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Flag_of_the_Solomon_Islands.svg/40px-Flag_of_the_Solomon_Islands.svg.png',ko:'솔로몬 제도', num:90,en:'Solomon Islands'} },
  [IOS3166_1_Code.SDN]: { description: '', data: {emoji:'🇸🇩', alpha2: 'SD', alpha3:'SDN', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Sudan.svg/22px-Flag_of_Sudan.svg.png',ko:'수단', num:729,en:'means'} },
  [IOS3166_1_Code.SUR]: { description: '', data: {emoji:'🇸🇷', alpha2: 'SR', alpha3:'SUR', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Flag_of_Suriname.svg/40px-Flag_of_Suriname.svg.png',ko:'수리남', num:740,en:'Suriname'} },
  [IOS3166_1_Code.LKA]: { description: '', data: {emoji:'🇱🇰', alpha2: 'LK', alpha3:'LKA', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Sri_Lanka.svg/40px-Flag_of_Sri_Lanka.svg.png',ko:'스리랑카', num:144,en:'Sri Lanka'} },
  [IOS3166_1_Code.SJM]: { description: '', data: {emoji:'🇸🇯', alpha2: 'SJ', alpha3:'SJM', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Proposed_flag_of_Svalbard%2C_Norway_%281930%29.svg/22px-Proposed_flag_of_Svalbard%2C_Norway_%281930%29.svg.png',ko:'스발바르 얀마옌', num:744,en:'Svalbard Janmayen'} },
  [IOS3166_1_Code.SWE]: { description: '', data: {emoji:'🇸🇪', alpha2: 'SE', alpha3:'SWE', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Sweden.svg/40px-Flag_of_Sweden.svg.png',ko:'스웨덴', num:752,en:'Sweden'} },
  [IOS3166_1_Code.CHE]: { description: '', data: {emoji:'🇨🇭', alpha2: 'CH', alpha3:'CHE', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/20px-Flag_of_Switzerland.svg.png',ko:'스위스', num:756,en:'Switzerland'} },
  [IOS3166_1_Code.ESP]: { description: '', data: {emoji:'🇪🇸', alpha2: 'ES', alpha3:'ESP', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/40px-Flag_of_Spain.svg.png',ko:'스페인', num:724,en:'Spain'} },
  [IOS3166_1_Code.SVK]: { description: '', data: {emoji:'🇸🇰', alpha2: 'SK', alpha3:'SVK', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Slovakia.svg/22px-Flag_of_Slovakia.svg.png',ko:'슬로바키아', num:703,en:'Slovakia'} },
  [IOS3166_1_Code.SVN]: { description: '', data: {emoji:'🇸🇮', alpha2: 'SI', alpha3:'SVN', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Flag_of_Slovenia.svg/22px-Flag_of_Slovenia.svg.png',ko:'슬로베니아', num:705,en:'Slovenia'} },
  [IOS3166_1_Code.SYR]: { description: '', data: {emoji:'🇸🇾', alpha2: 'SY', alpha3:'SYR', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Flag_of_the_Syrian_revolution.svg/40px-Flag_of_the_Syrian_revolution.svg.png',ko:'시리아', num:760,en:'Syria'} },
  [IOS3166_1_Code.SLE]: { description: '', data: {emoji:'🇸🇱', alpha2: 'SL', alpha3:'SLE', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Sierra_Leone.svg/22px-Flag_of_Sierra_Leone.svg.png',ko:'시에라리온', num:694,en:'Sierra Leone'} },
  [IOS3166_1_Code.SXM]: { description: '', data: {emoji:'🇸🇽', alpha2: 'SX', alpha3:'SXM', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Sint_Maarten.svg/40px-Flag_of_Sint_Maarten.svg.png',ko:'신트마르턴', num:534,en:'Sint Marton'} },
  [IOS3166_1_Code.SGP]: { description: '', data: {emoji:'🇸🇬', alpha2: 'SG', alpha3:'SGP', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/22px-Flag_of_Singapore.svg.png',ko:'싱가포르', num:702,en:'Singapore'} },
  [IOS3166_1_Code.ARE]: { description: '', data: {emoji:'🇦🇪', alpha2: 'AE', alpha3:'ARE', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_United_Arab_Emirates.svg/40px-Flag_of_the_United_Arab_Emirates.svg.png',ko:'아랍에미리트', num:784,en:'United Arab Emirates'} },
  [IOS3166_1_Code.ABW]: { description: '', data: {emoji:'🇦🇼', alpha2: 'AW', alpha3:'ABW', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Aruba.svg/22px-Flag_of_Aruba.svg.png',ko:'아루바', num:533,en:'Aruba'} },
  [IOS3166_1_Code.ARM]: { description: '', data: {emoji:'🇦🇲', alpha2: 'AM', alpha3:'ARM', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Flag_of_Armenia.svg/40px-Flag_of_Armenia.svg.png',ko:'아르메니아', num:51,en:'Armenia'} },
  [IOS3166_1_Code.ARG]: { description: '', data: {emoji:'🇦🇷', alpha2: 'AR', alpha3:'ARG', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/22px-Flag_of_Argentina.svg.png',ko:'아르헨티나', num:32,en:'Argentina'} },
  [IOS3166_1_Code.ASM]: { description: '', data: {emoji:'🇦🇸', alpha2: 'AS', alpha3:'ASM', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Flag_of_American_Samoa.svg/40px-Flag_of_American_Samoa.svg.png',ko:'아메리칸사모아', num:16,en:'American Samoa'} },
  [IOS3166_1_Code.ISL]: { description: '', data: {emoji:'🇮🇸', alpha2: 'IS', alpha3:'ISL', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Iceland.svg/40px-Flag_of_Iceland.svg.png',ko:'아이슬란드', num:352,en:'Iceland'} },
  [IOS3166_1_Code.HTI]: { description: '', data: {emoji:'🇭🇹', alpha2: 'HT', alpha3:'HTI', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Haiti.svg/40px-Flag_of_Haiti.svg.png',ko:'아이티', num:332,en:'Haiti'} },
  [IOS3166_1_Code.IRL]: { description: '', data: {emoji:'🇮🇪', alpha2: 'IE', alpha3:'IRL', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Flag_of_Ireland.svg/40px-Flag_of_Ireland.svg.png',ko:'아일랜드', num:372,en:'Ireland'} },
  [IOS3166_1_Code.AZE]: { description: '', data: {emoji:'🇦🇿', alpha2: 'AZ', alpha3:'AZE', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/40px-Flag_of_Azerbaijan.svg.png',ko:'아제르바이잔', num:31,en:'Azerbaijan'} },
  [IOS3166_1_Code.AFG]: { description: '', data: {emoji:'🇦🇫', alpha2: 'AF', alpha3:'AFG', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/40px-Flag_of_the_Taliban.svg.png',ko:'아프가니스탄', num:4,en:'Afghanistan'} },
  [IOS3166_1_Code.AND]: { description: '', data: {emoji:'🇦🇩', alpha2: 'AD', alpha3:'AND', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Andorra.svg/22px-Flag_of_Andorra.svg.png',ko:'안도라', num:20,en:'Andorra'} },
  [IOS3166_1_Code.ALB]: { description: '', data: {emoji:'🇦🇱', alpha2: 'AL', alpha3:'ALB', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/40px-Flag_of_Albania.svg.png',ko:'알바니아', num:8,en:'Albania'} },
  [IOS3166_1_Code.DZA]: { description: '', data: {emoji:'🇩🇿', alpha2: 'DZ', alpha3:'DZA', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/40px-Flag_of_Algeria.svg.png',ko:'알제리', num:12,en:'Algeria'} },
  [IOS3166_1_Code.AGO]: { description: '', data: {emoji:'🇦🇴', alpha2: 'AO', alpha3:'AGO', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Angola.svg/22px-Flag_of_Angola.svg.png',ko:'앙골라', num:24,en:'Angola'} },
  [IOS3166_1_Code.ATG]: { description: '', data: {emoji:'🇦🇬', alpha2: 'AG', alpha3:'ATG', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Antigua_and_Barbuda.svg/22px-Flag_of_Antigua_and_Barbuda.svg.png',ko:'앤티가 바부다', num:28,en:'be full of antis'} },
  [IOS3166_1_Code.AIA]: { description: '', data: {emoji:'🇦🇮', alpha2: 'AI', alpha3:'AIA', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Anguilla.svg/40px-Flag_of_Anguilla.svg.png',ko:'앵귈라', num:660,en:'Anguilla'} },
  [IOS3166_1_Code.ERI]: { description: '', data: {emoji:'🇪🇷', alpha2: 'ER', alpha3:'ERI', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Flag_of_Eritrea.svg/40px-Flag_of_Eritrea.svg.png',ko:'에리트레아', num:232,en:'Eritrea'} },
  [IOS3166_1_Code.SWZ]: { description: '', data: {emoji:'🇸🇿', alpha2: 'SZ', alpha3:'SWZ', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Flag_of_Eswatini.svg/22px-Flag_of_Eswatini.svg.png',ko:'에스와티니', num:748,en:'Eswatini'} },
  [IOS3166_1_Code.EST]: { description: '', data: {emoji:'🇪🇪', alpha2: 'EE', alpha3:'EST', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Flag_of_Estonia.svg/22px-Flag_of_Estonia.svg.png',ko:'에스토니아', num:233,en:'Estonia'} },
  [IOS3166_1_Code.ECU]: { description: '', data: {emoji:'🇪🇨', alpha2: 'EC', alpha3:'ECU', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/40px-Flag_of_Ecuador.svg.png',ko:'에콰도르', num:218,en:'Ecuador'} },
  [IOS3166_1_Code.ETH]: { description: '', data: {emoji:'🇪🇹', alpha2: 'ET', alpha3:'ETH', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Ethiopia.svg/22px-Flag_of_Ethiopia.svg.png',ko:'에티오피아', num:231,en:'Ethiopia'} },
  [IOS3166_1_Code.SLV]: { description: '', data: {emoji:'🇸🇻', alpha2: 'SV', alpha3:'SLV', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_El_Salvador.svg/22px-Flag_of_El_Salvador.svg.png',ko:'엘살바도르', num:222,en:'El Salvador'} },
  [IOS3166_1_Code.GBR]: { description: '', data: {emoji:'🇬🇧', alpha2: 'GB', alpha3:'GBR', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Flag_of_the_United_Kingdom_%281-2%29.svg/40px-Flag_of_the_United_Kingdom_%281-2%29.svg.png',ko:'영국', num:826,en:'the United Kingdom'} },
  [IOS3166_1_Code.VGB]: { description: '', data: {emoji:'🇻🇬', alpha2: 'VG', alpha3:'VGB', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Flag_of_the_British_Virgin_Islands.svg/40px-Flag_of_the_British_Virgin_Islands.svg.png',ko:'영국령 버진아일랜드', num:92,en:'British Virgin Islands'} },
  [IOS3166_1_Code.IOT]: { description: '', data: {emoji:'🇮🇴', alpha2: 'IO', alpha3:'IOT', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_the_Commissioner_of_the_British_Indian_Ocean_Territory.svg/22px-Flag_of_the_Commissioner_of_the_British_Indian_Ocean_Territory.svg.png',ko:'영국령 인도양 지역', num:86,en:'the British Indian Ocean region'} },
  [IOS3166_1_Code.YEM]: { description: '', data: {emoji:'🇾🇪', alpha2: 'YE', alpha3:'YEM', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Yemen.svg/40px-Flag_of_Yemen.svg.png',ko:'예멘', num:887,en:'Yemen'} },
  [IOS3166_1_Code.OMN]: { description: '', data: {emoji:'🇴🇲', alpha2: 'OM', alpha3:'OMN', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Oman.svg/40px-Flag_of_Oman.svg.png',ko:'오만', num:512,en:'arrogance'} },
  [IOS3166_1_Code.AUS]: { description: '', data: {emoji:'🇦🇺', alpha2: 'AU', alpha3:'AUS', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Australia.svg/40px-Flag_of_Australia.svg.png',ko:'오스트레일리아', num:36,en:'Australia'} },
  [IOS3166_1_Code.AUT]: { description: '', data: {emoji:'🇦🇹', alpha2: 'AT', alpha3:'AUT', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/22px-Flag_of_Austria.svg.png',ko:'오스트리아', num:40,en:'Austria'} },
  [IOS3166_1_Code.HND]: { description: '', data: {emoji:'🇭🇳', alpha2: 'HN', alpha3:'HND', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Flag_of_Honduras.svg/40px-Flag_of_Honduras.svg.png',ko:'온두라스', num:340,en:'Honduras'} },
  [IOS3166_1_Code.ALA]: { description: '', data: {emoji:'🇦🇽', alpha2: 'AX', alpha3:'ALA', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Flag_of_%C3%85land.svg/40px-Flag_of_%C3%85land.svg.png',ko:'올란드 제도', num:248,en:'the Orland Islands'} },
  [IOS3166_1_Code.JOR]: { description: '', data: {emoji:'🇯🇴', alpha2: 'JO', alpha3:'JOR', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Flag_of_Jordan.svg/40px-Flag_of_Jordan.svg.png',ko:'요르단', num:400,en:'Jordan'} },
  [IOS3166_1_Code.UGA]: { description: '', data: {emoji:'🇺🇬', alpha2: 'UG', alpha3:'UGA', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Flag_of_Uganda.svg/22px-Flag_of_Uganda.svg.png',ko:'우간다', num:800,en:'Uganda'} },
  [IOS3166_1_Code.URY]: { description: '', data: {emoji:'🇺🇾', alpha2: 'UY', alpha3:'URY', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/22px-Flag_of_Uruguay.svg.png',ko:'우루과이', num:858,en:'Uruguay'} },
  [IOS3166_1_Code.UZB]: { description: '', data: {emoji:'🇺🇿', alpha2: 'UZ', alpha3:'UZB', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Uzbekistan.svg/40px-Flag_of_Uzbekistan.svg.png',ko:'우즈베키스탄', num:860,en:'Uzbekistan'} },
  [IOS3166_1_Code.UKR]: { description: '', data: {emoji:'🇺🇦', alpha2: 'UA', alpha3:'UKR', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Ukraine.svg/22px-Flag_of_Ukraine.svg.png',ko:'우크라이나', num:804,en:'Ukraine'} },
  [IOS3166_1_Code.WLF]: { description: '', data: {emoji:'🇼🇫', alpha2: 'WF', alpha3:'WLF', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Flag_of_France_%282020%E2%80%93present%29.svg/22px-Flag_of_France_%282020%E2%80%93present%29.svg.png',ko:'왈리스 푸투나', num:876,en:'Wallis Putuna'} },
  [IOS3166_1_Code.IRQ]: { description: '', data: {emoji:'🇮🇶', alpha2: 'IQ', alpha3:'IRQ', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Iraq.svg/40px-Flag_of_Iraq.svg.png',ko:'이라크', num:368,en:'Iraq'} },
  [IOS3166_1_Code.IRN]: { description: '', data: {emoji:'🇮🇷', alpha2: 'IR', alpha3:'IRN', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/40px-Flag_of_Iran.svg.png',ko:'이란', num:364,en:'Iran'} },
  [IOS3166_1_Code.ISR]: { description: '', data: {emoji:'🇮🇱', alpha2: 'IL', alpha3:'ISR', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/22px-Flag_of_Israel.svg.png',ko:'이스라엘', num:376,en:'Israel'} },
  [IOS3166_1_Code.EGY]: { description: '', data: {emoji:'🇪🇬', alpha2: 'EG', alpha3:'EGY', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/22px-Flag_of_Egypt.svg.png',ko:'이집트', num:818,en:'Egypt.'} },
  [IOS3166_1_Code.ITA]: { description: '', data: {emoji:'🇮🇹', alpha2: 'IT', alpha3:'ITA', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Flag_of_Italy.svg/40px-Flag_of_Italy.svg.png',ko:'이탈리아', num:380,en:'Italy'} },
  [IOS3166_1_Code.IND]: { description: '', data: {emoji:'🇮🇳', alpha2: 'IN', alpha3:'IND', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_India.svg/22px-Flag_of_India.svg.png',ko:'인도', num:356,en:'India'} },
  [IOS3166_1_Code.IDN]: { description: '', data: {emoji:'🇮🇩', alpha2: 'ID', alpha3:'IDN', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/22px-Flag_of_Indonesia.svg.png',ko:'인도네시아', num:360,en:'Indonesia'} },
  [IOS3166_1_Code.JPN]: { description: '', data: {emoji:'🇯🇵', alpha2: 'JP', alpha3:'JPN', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/40px-Flag_of_Japan.svg.png',ko:'일본', num:392,en:'Japan'} },
  [IOS3166_1_Code.JAM]: { description: '', data: {emoji:'🇯🇲', alpha2: 'JM', alpha3:'JAM', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Jamaica.svg/40px-Flag_of_Jamaica.svg.png',ko:'자메이카', num:388,en:'Jamaica'} },
  [IOS3166_1_Code.ZMB]: { description: '', data: {emoji:'🇿🇲', alpha2: 'ZM', alpha3:'ZMB', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Zambia.svg/40px-Flag_of_Zambia.svg.png',ko:'잠비아', num:894,en:'Zambia'} },
  [IOS3166_1_Code.JEY]: { description: '', data: {emoji:'🇯🇪', alpha2: 'JE', alpha3:'JEY', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Flag_of_Jersey.svg/22px-Flag_of_Jersey.svg.png',ko:'저지섬', num:832,en:'Jersey Island'} },
  [IOS3166_1_Code.GNQ]: { description: '', data: {emoji:'🇬🇶', alpha2: 'GQ', alpha3:'GNQ', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Equatorial_Guinea.svg/40px-Flag_of_Equatorial_Guinea.svg.png',ko:'적도 기니', num:226,en:'Equatorial Guinea'} },
  [IOS3166_1_Code.PRK]: { description: '', data: {emoji:'🇰🇵', alpha2: 'KP', alpha3:'PRK', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Flag_of_North_Korea.svg/40px-Flag_of_North_Korea.svg.png',ko:'조선민주주의인민공화국', num:408,en:'Democratic People\'s Republic of Korea'} },
  [IOS3166_1_Code.GEO]: { description: '', data: {emoji:'🇬🇪', alpha2: 'GE', alpha3:'GEO', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Georgia.svg/40px-Flag_of_Georgia.svg.png',ko:'조지아', num:268,en:'Georgia'} },
  [IOS3166_1_Code.CHN]: { description: '', data: {emoji:'🇨🇳', alpha2: 'CN', alpha3:'CHN', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/22px-Flag_of_the_People%27s_Republic_of_China.svg.png',ko:'중국', num:156,en:'China'} },
  [IOS3166_1_Code.CAF]: { description: '', data: {emoji:'🇨🇫', alpha2: 'CF', alpha3:'CAF', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Central_African_Republic.svg/22px-Flag_of_the_Central_African_Republic.svg.png',ko:'중앙아프리카 공화국', num:140,en:'Central African Republic'} },
  [IOS3166_1_Code.DJI]: { description: '', data: {emoji:'🇩🇯', alpha2: 'DJ', alpha3:'DJI', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_Djibouti.svg/40px-Flag_of_Djibouti.svg.png',ko:'지부티', num:262,en:'Djibouti'} },
  [IOS3166_1_Code.GIB]: { description: '', data: {emoji:'🇬🇮', alpha2: 'GI', alpha3:'GIB', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Flag_of_Gibraltar.svg/40px-Flag_of_Gibraltar.svg.png',ko:'지브롤터', num:292,en:'Gibraltar'} },
  [IOS3166_1_Code.ZWE]: { description: '', data: {emoji:'🇿🇼', alpha2: 'ZW', alpha3:'ZWE', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Flag_of_Zimbabwe.svg/40px-Flag_of_Zimbabwe.svg.png',ko:'짐바브웨', num:716,en:'Zimbabwe'} },
  [IOS3166_1_Code.TCD]: { description: '', data: {emoji:'🇹🇩', alpha2: 'TD', alpha3:'TCD', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Flag_of_Chad.svg/40px-Flag_of_Chad.svg.png',ko:'차드', num:148,en:'Chad'} },
  [IOS3166_1_Code.CZE]: { description: '', data: {emoji:'🇨🇿', alpha2: 'CZ', alpha3:'CZE', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_Czech_Republic.svg/40px-Flag_of_the_Czech_Republic.svg.png',ko:'체코', num:203,en:'Czech Republic'} },
  [IOS3166_1_Code.CHL]: { description: '', data: {emoji:'🇨🇱', alpha2: 'CL', alpha3:'CHL', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/40px-Flag_of_Chile.svg.png',ko:'칠레', num:152,en:'Chile'} },
  [IOS3166_1_Code.CMR]: { description: '', data: {emoji:'🇨🇲', alpha2: 'CM', alpha3:'CMR', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/40px-Flag_of_Cameroon.svg.png',ko:'카메룬', num:120,en:'Cameroon'} },
  [IOS3166_1_Code.CPV]: { description: '', data: {emoji:'🇨🇻', alpha2: 'CV', alpha3:'CPV', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Cape_Verde.svg/40px-Flag_of_Cape_Verde.svg.png',ko:'카보베르데', num:132,en:'Cabo Verde'} },
  [IOS3166_1_Code.KAZ]: { description: '', data: {emoji:'🇰🇿', alpha2: 'KZ', alpha3:'KAZ', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kazakhstan.svg/40px-Flag_of_Kazakhstan.svg.png',ko:'카자흐스탄', num:398,en:'Kazakhstan'} },
  [IOS3166_1_Code.QAT]: { description: '', data: {emoji:'🇶🇦', alpha2: 'QA', alpha3:'QAT', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/22px-Flag_of_Qatar.svg.png',ko:'카타르', num:634,en:'Qatar'} },
  [IOS3166_1_Code.KHM]: { description: '', data: {emoji:'🇰🇭', alpha2: 'KH', alpha3:'KHM', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_Cambodia.svg/22px-Flag_of_Cambodia.svg.png',ko:'캄보디아', num:116,en:'Cambodia'} },
  [IOS3166_1_Code.CAN]: { description: '', data: {emoji:'🇨🇦', alpha2: 'CA', alpha3:'CAN', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Canada.svg/22px-Flag_of_Canada.svg.png',ko:'캐나다', num:124,en:'Canada'} },
  [IOS3166_1_Code.KEN]: { description: '', data: {emoji:'🇰🇪', alpha2: 'KE', alpha3:'KEN', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Kenya.svg/40px-Flag_of_Kenya.svg.png',ko:'케냐', num:404,en:'Kenya'} },
  [IOS3166_1_Code.CYM]: { description: '', data: {emoji:'🇰🇾', alpha2: 'KY', alpha3:'CYM', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_the_Cayman_Islands.svg/22px-Flag_of_the_Cayman_Islands.svg.png',ko:'케이맨 제도', num:136,en:'Cayman Islands'} },
  [IOS3166_1_Code.COM]: { description: '', data: {emoji:'🇰🇲', alpha2: 'KM', alpha3:'COM', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Flag_of_the_Comoros.svg/40px-Flag_of_the_Comoros.svg.png',ko:'코모로', num:174,en:'Comoros'} },
  [IOS3166_1_Code.CRI]: { description: '', data: {emoji:'🇨🇷', alpha2: 'CR', alpha3:'CRI', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Flag_of_Costa_Rica.svg/40px-Flag_of_Costa_Rica.svg.png',ko:'코스타리카', num:188,en:'Costa Rica'} },
  [IOS3166_1_Code.CCK]: { description: '', data: {emoji:'🇨🇨', alpha2: 'CC', alpha3:'CCK', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Flag_of_the_Cocos_%28Keeling%29_Islands.svg/40px-Flag_of_the_Cocos_%28Keeling%29_Islands.svg.png',ko:'코코스 제도', num:166,en:'Cocos Islands'} },
  [IOS3166_1_Code.CIV]: { description: '', data: {emoji:'🇨🇮', alpha2: 'CI', alpha3:'CIV', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_C%C3%B4te_d%27Ivoire.svg/40px-Flag_of_C%C3%B4te_d%27Ivoire.svg.png',ko:'코트디부아르', num:384,en:'Ivory Coast'} },
  [IOS3166_1_Code.COL]: { description: '', data: {emoji:'🇨🇴', alpha2: 'CO', alpha3:'COL', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/40px-Flag_of_Colombia.svg.png',ko:'콜롬비아', num:170,en:'Colombia'} },
  [IOS3166_1_Code.COG]: { description: '', data: {emoji:'🇨🇬', alpha2: 'CG', alpha3:'COG', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_the_Republic_of_the_Congo.svg/40px-Flag_of_the_Republic_of_the_Congo.svg.png',ko:'콩고 공화국', num:178,en:'Republic of Congo'} },
  [IOS3166_1_Code.COD]: { description: '', data: {emoji:'🇨🇩', alpha2: 'CD', alpha3:'COD', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg/22px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png',ko:'콩고 민주 공화국', num:180,en:'Democratic Republic of the Congo'} },
  [IOS3166_1_Code.CUB]: { description: '', data: {emoji:'🇨🇺', alpha2: 'CU', alpha3:'CUB', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Flag_of_Cuba.svg/40px-Flag_of_Cuba.svg.png',ko:'쿠바', num:192,en:'Cuba'} },
  [IOS3166_1_Code.KWT]: { description: '', data: {emoji:'🇰🇼', alpha2: 'KW', alpha3:'KWT', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Flag_of_Kuwait.svg/40px-Flag_of_Kuwait.svg.png',ko:'쿠웨이트', num:414,en:'Kuwait'} },
  [IOS3166_1_Code.COK]: { description: '', data: {emoji:'🇨🇰', alpha2: 'CK', alpha3:'COK', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Flag_of_the_Cook_Islands.svg/40px-Flag_of_the_Cook_Islands.svg.png',ko:'쿡 제도', num:184,en:'Cook Islands'} },
  [IOS3166_1_Code.CUW]: { description: '', data: {emoji:'🇨🇼', alpha2: 'CW', alpha3:'CUW', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Flag_of_Cura%C3%A7ao.svg/40px-Flag_of_Cura%C3%A7ao.svg.png',ko:'퀴라소', num:531,en:'Curaçao'} },
  [IOS3166_1_Code.HRV]: { description: '', data: {emoji:'🇭🇷', alpha2: 'HR', alpha3:'HRV', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/40px-Flag_of_Croatia.svg.png',ko:'크로아티아', num:191,en:'Croatia'} },
  [IOS3166_1_Code.CXR]: { description: '', data: {emoji:'🇨🇽', alpha2: 'CX', alpha3:'CXR', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Flag_of_Christmas_Island.svg/22px-Flag_of_Christmas_Island.svg.png',ko:'크리스마스섬', num:162,en:'Christmas Island'} },
  [IOS3166_1_Code.KGZ]: { description: '', data: {emoji:'🇰🇬', alpha2: 'KG', alpha3:'KGZ', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Flag_of_Kyrgyzstan.svg/22px-Flag_of_Kyrgyzstan.svg.png',ko:'키르기스스탄', num:417,en:'Kyrgyzstan'} },
  [IOS3166_1_Code.KIR]: { description: '', data: {emoji:'🇰🇮', alpha2: 'KI', alpha3:'KIR', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kiribati.svg/22px-Flag_of_Kiribati.svg.png',ko:'키리바시', num:296,en:'Kiribati'} },
  [IOS3166_1_Code.CYP]: { description: '', data: {emoji:'🇨🇾', alpha2: 'CY', alpha3:'CYP', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Cyprus.svg/22px-Flag_of_Cyprus.svg.png',ko:'키프로스', num:196,en:'Cyprus'} },
  [IOS3166_1_Code.TWN]: { description: '', data: {emoji:'🇹🇼', alpha2: 'TW', alpha3:'TWN', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/40px-Flag_of_the_Republic_of_China.svg.png',ko:'대만', num:158,en:'Taiwan'} },
  [IOS3166_1_Code.TJK]: { description: '', data: {emoji:'🇹🇯', alpha2: 'TJ', alpha3:'TJK', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Tajikistan.svg/40px-Flag_of_Tajikistan.svg.png',ko:'타지키스탄', num:762,en:'Tajikistan'} },
  [IOS3166_1_Code.TZA]: { description: '', data: {emoji:'🇹🇿', alpha2: 'TZ', alpha3:'TZA', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tanzania.svg/40px-Flag_of_Tanzania.svg.png',ko:'탄자니아', num:834,en:'Tanzania'} },
  [IOS3166_1_Code.THA]: { description: '', data: {emoji:'🇹🇭', alpha2: 'TH', alpha3:'THA', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/22px-Flag_of_Thailand.svg.png',ko:'태국', num:764,en:'Thailand'} },
  [IOS3166_1_Code.TCA]: { description: '', data: {emoji:'🇹🇨', alpha2: 'TC', alpha3:'TCA', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_the_Turks_and_Caicos_Islands.svg/40px-Flag_of_the_Turks_and_Caicos_Islands.svg.png',ko:'터크스 케이커스 제도', num:796,en:'Turks and Caicos Islands'} },
  [IOS3166_1_Code.TUR]: { description: '', data: {emoji:'🇹🇷', alpha2: 'TR', alpha3:'TUR', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/22px-Flag_of_Turkey.svg.png',ko:'튀르키예', num:792,en:'Turkiye'} },
  [IOS3166_1_Code.TGO]: { description: '', data: {emoji:'🇹🇬', alpha2: 'TG', alpha3:'TGO', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Flag_of_Togo_%283-2%29.svg/40px-Flag_of_Togo_%283-2%29.svg.png',ko:'토고', num:768,en:'Togo'} },
  [IOS3166_1_Code.TKL]: { description: '', data: {emoji:'🇹🇰', alpha2: 'TK', alpha3:'TKL', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Flag_of_Tokelau.svg/40px-Flag_of_Tokelau.svg.png',ko:'토켈라우', num:772,en:'Tokelau'} },
  [IOS3166_1_Code.TON]: { description: '', data: {emoji:'🇹🇴', alpha2: 'TO', alpha3:'TON', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Tonga.svg/22px-Flag_of_Tonga.svg.png',ko:'통가', num:776,en:'the whole house'} },
  [IOS3166_1_Code.TKM]: { description: '', data: {emoji:'🇹🇲', alpha2: 'TM', alpha3:'TKM', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Turkmenistan.svg/40px-Flag_of_Turkmenistan.svg.png',ko:'투르크메니스탄', num:795,en:'Turkmenistan'} },
  [IOS3166_1_Code.TUV]: { description: '', data: {emoji:'🇹🇻', alpha2: 'TV', alpha3:'TUV', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tuvalu.svg/40px-Flag_of_Tuvalu.svg.png',ko:'투발루', num:798,en:'Tuvalu'} },
  [IOS3166_1_Code.TUN]: { description: '', data: {emoji:'🇹🇳', alpha2: 'TN', alpha3:'TUN', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/40px-Flag_of_Tunisia.svg.png',ko:'튀니지', num:788,en:'Tunisia'} },
  [IOS3166_1_Code.TTO]: { description: '', data: {emoji:'🇹🇹', alpha2: 'TT', alpha3:'TTO', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Trinidad_and_Tobago.svg/40px-Flag_of_Trinidad_and_Tobago.svg.png',ko:'트리니다드 토바고', num:780,en:'Trinidad and Tobago'} },
  [IOS3166_1_Code.PAN]: { description: '', data: {emoji:'🇵🇦', alpha2: 'PA', alpha3:'PAN', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Flag_of_Panama.svg/40px-Flag_of_Panama.svg.png',ko:'파나마', num:591,en:'Panama'} },
  [IOS3166_1_Code.PRY]: { description: '', data: {emoji:'🇵🇾', alpha2: 'PY', alpha3:'PRY', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Paraguay.svg/40px-Flag_of_Paraguay.svg.png',ko:'파라과이', num:600,en:'Paraguay'} },
  [IOS3166_1_Code.PAK]: { description: '', data: {emoji:'🇵🇰', alpha2: 'PK', alpha3:'PAK', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Pakistan.svg/40px-Flag_of_Pakistan.svg.png',ko:'파키스탄', num:586,en:'Pakistan'} },
  [IOS3166_1_Code.PNG]: { description: '', data: {emoji:'🇵🇬', alpha2: 'PG', alpha3:'PNG', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Flag_of_Papua_New_Guinea.svg/22px-Flag_of_Papua_New_Guinea.svg.png',ko:'파푸아뉴기니', num:598,en:'Papua New Guinea'} },
  [IOS3166_1_Code.PLW]: { description: '', data: {emoji:'🇵🇼', alpha2: 'PW', alpha3:'PLW', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Palau.svg/22px-Flag_of_Palau.svg.png',ko:'팔라우', num:585,en:'Palau'} },
  [IOS3166_1_Code.PSE]: { description: '', data: {emoji:'🇵🇸', alpha2: 'PS', alpha3:'PSE', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Palestine.svg/40px-Flag_of_Palestine.svg.png',ko:'팔레스타인', num:275,en:'Palestine'} },
  [IOS3166_1_Code.FRO]: { description: '', data: {emoji:'🇫🇴', alpha2: 'FO', alpha3:'FRO', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Flag_of_the_Faroe_Islands.svg/40px-Flag_of_the_Faroe_Islands.svg.png',ko:'페로 제도', num:234,en:'Faroe Islands'} },
  [IOS3166_1_Code.PER]: { description: '', data: {emoji:'🇵🇪', alpha2: 'PE', alpha3:'PER', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Peru.svg/40px-Flag_of_Peru.svg.png',ko:'페루', num:604,en:'Peru, Republic of'} },
  [IOS3166_1_Code.PRT]: { description: '', data: {emoji:'🇵🇹', alpha2: 'PT', alpha3:'PRT', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/22px-Flag_of_Portugal.svg.png',ko:'포르투갈', num:620,en:'Portugal'} },
  [IOS3166_1_Code.FLK]: { description: '', data: {emoji:'🇫🇰', alpha2: 'FK', alpha3:'FLK', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_the_Falkland_Islands.svg/40px-Flag_of_the_Falkland_Islands.svg.png',ko:'포클랜드 제도', num:238,en:'Falkland Islands'} },
  [IOS3166_1_Code.POL]: { description: '', data: {emoji:'🇵🇱', alpha2: 'PL', alpha3:'POL', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Flag_of_Poland.svg/22px-Flag_of_Poland.svg.png',ko:'폴란드', num:616,en:'Poland'} },
  [IOS3166_1_Code.PRI]: { description: '', data: {emoji:'🇵🇷', alpha2: 'PR', alpha3:'PRI', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Flag_of_Puerto_Rico.svg/40px-Flag_of_Puerto_Rico.svg.png',ko:'푸에르토리코', num:630,en:'Puerto Rico'} },
  [IOS3166_1_Code.FRA]: { description: '', data: {emoji:'🇫🇷', alpha2: 'FR', alpha3:'FRA', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Flag_of_France_%282024%E2%80%93present%29.svg/40px-Flag_of_France_%282024%E2%80%93present%29.svg.png',ko:'프랑스', num:250,en:'France'} },
  [IOS3166_1_Code.GUF]: { description: '', data: {emoji:'🇬🇫', alpha2: 'GF', alpha3:'GUF', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Flag_of_French_Guiana.svg/22px-Flag_of_French_Guiana.svg.png',ko:'프랑스령 기아나', num:254,en:'French Guiana'} },
  [IOS3166_1_Code.ATF]: { description: '', data: {emoji:'🇹🇫', alpha2: 'TF', alpha3:'ATF', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Flag_of_the_French_Southern_and_Antarctic_Lands.svg/22px-Flag_of_the_French_Southern_and_Antarctic_Lands.svg.png',ko:'프랑스령 남방 및 남극 지역', num:260,en:'French Southern and Antarctic regions'} },
  [IOS3166_1_Code.PYF]: { description: '', data: {emoji:'🇵🇫', alpha2: 'PF', alpha3:'PYF', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Flag_of_French_Polynesia.svg/22px-Flag_of_French_Polynesia.svg.png',ko:'프랑스령 폴리네시아', num:258,en:'French Polynesia'} },
  [IOS3166_1_Code.FJI]: { description: '', data: {emoji:'🇫🇯', alpha2: 'FJ', alpha3:'FJI', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Fiji.svg/22px-Flag_of_Fiji.svg.png',ko:'피지', num:242,en:'Fiji'} },
  [IOS3166_1_Code.FIN]: { description: '', data: {emoji:'🇫🇮', alpha2: 'FI', alpha3:'FIN', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Finland.svg/40px-Flag_of_Finland.svg.png',ko:'핀란드', num:246,en:'Finland'} },
  [IOS3166_1_Code.PHL]: { description: '', data: {emoji:'🇵🇭', alpha2: 'PH', alpha3:'PHL', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_the_Philippines.svg/40px-Flag_of_the_Philippines.svg.png',ko:'필리핀', num:608,en:'Philippines'} },
  [IOS3166_1_Code.PCN]: { description: '', data: {emoji:'🇵🇳', alpha2: 'PN', alpha3:'PCN', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_the_Pitcairn_Islands.svg/22px-Flag_of_the_Pitcairn_Islands.svg.png',ko:'핏케언 제도', num:612,en:'Pitcairn Islands'} },
  [IOS3166_1_Code.HMD]: { description: '', data: {emoji:'🇭🇲', alpha2: 'HM', alpha3:'HMD', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Australia.svg/40px-Flag_of_Australia.svg.png',ko:'허드 맥도널드 제도', num:334,en:'the Heard MacDonald Islands'} },
  [IOS3166_1_Code.HUN]: { description: '', data: {emoji:'🇭🇺', alpha2: 'HU', alpha3:'HUN', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Flag_of_Hungary.svg/40px-Flag_of_Hungary.svg.png',ko:'헝가리', num:348,en:'Hungary'} },
  [IOS3166_1_Code.HKG]: { description: '', data: {emoji:'🇭🇰', alpha2: 'HK', alpha3:'HKG', img:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Flag_of_Hong_Kong.svg/22px-Flag_of_Hong_Kong.svg.png',ko:'홍콩', num:344,en:'Hong Kong'} },
};